spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

aws.eventBridge.bus=default-event-bus

JWT_SECRET=a-long-enough-secret-key-for-hmac-sha256-at-least-32-bytes